import type { LucideIcon } from 'lucide-react';
import { ArrowDownRight,ArrowUpRight,Inbox } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { formatCurrency } from '@/utils/money';
import type { DashboardData,FinancialRecord } from '@/validations/dashboard';

export function CurrencyDisplay({value,hidden=false,className}:{value:string;hidden?:boolean;className?:string}) {return <span className={cn('wr-money whitespace-nowrap',className)} aria-label={hidden?'Valor oculto':undefined}>{hidden?'••••••':formatCurrency(value)}</span>;}
export function FinancialCard({title,value,icon:Icon,tone='neutral',description,hidden,featured=false,comparison}:{title:string;value:string;icon:LucideIcon;tone?:'positive'|'negative'|'neutral'|'info';description:string;hidden?:boolean;featured?:boolean;comparison?:string}) {
  return <section className={cn('wr-section p-5 transition-shadow hover:shadow-md xl:p-6',featured&&'wr-featured')}><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-sm font-medium text-muted-foreground">{title}</h2><span className={cn('flex size-10 shrink-0 items-center justify-center rounded-xl',tone==='positive'?'bg-positive/10 text-positive':tone==='negative'?'bg-negative/10 text-negative':tone==='info'?'bg-info/10 text-info':'bg-primary/10 text-primary')}><Icon className="size-5"/></span></div><CurrencyDisplay value={value} hidden={hidden} className={cn('block text-[clamp(1.4rem,2.05vw,2rem)] font-semibold leading-tight',title==='Resultado'&&(value.startsWith('-')?'text-negative':'text-positive'))}/><p className="mt-5 text-xs leading-5 text-muted-foreground">{comparison||description}</p></section>;
}
export function StatusBadge({status,type,dueDate,today}:{status:FinancialRecord['status'];type:FinancialRecord['type'];dueDate:string;today:string}) {
  const overdue=status==='pending'&&dueDate<today;
  return <span className={cn('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium',status==='paid'?'bg-positive/10 text-positive':status==='cancelled'?'bg-muted text-muted-foreground':overdue?'bg-negative/10 text-negative':'bg-warning/10 text-warning')}><span className="wr-dot"/>{status==='paid'?(type==='income'?'Recebido':'Pago'):status==='cancelled'?'Cancelado':overdue?'Vencido':'Pendente'}</span>;
}
export function EmptyState({title='Nenhuma transação encontrada',description='Comece adicionando sua primeira movimentação financeira.',action,onAction}:{title?:string;description?:string;action?:string;onAction?:()=>void}) {return <div className="flex min-h-56 flex-col items-center justify-center px-6 py-8 text-center"><span className="mb-4 rounded-2xl bg-muted p-4 text-muted-foreground"><Inbox className="size-6"/></span><h3 className="text-base font-medium">{title}</h3><p className="mt-2 max-w-xs text-sm leading-6 text-muted-foreground">{description}</p>{action&&<Button className="mt-5" onClick={onAction}>{action}</Button>}</div>;}
export function PageHeader({title,description,children}:{title:string;description:string;children?:React.ReactNode}) {return <header className="mb-7 flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><p className="mb-2 flex items-center gap-2 text-[10px] font-medium uppercase tracking-[.17em] text-muted-foreground"><span className="wr-dot text-primary"/>SEU NEGÓCIO EM PERSPECTIVA</p><h1 className="text-3xl font-semibold tracking-tight">{title}<span className="text-primary">.</span></h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div><div className="flex flex-wrap items-center gap-3">{children}</div></header>;}
export function AccountCard({account,hidden}:{account:DashboardData['accounts'][number];hidden?:boolean}) {return <section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{account.name}</h3><p className="mt-1 text-xs text-muted-foreground">{{bank:'Conta bancária',cash:'Dinheiro',pix:'Pix',wallet:'Carteira digital',card:'Cartão',other:'Outros'}[account.type]}{account.archived?' · Arquivada':''}</p></div><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-xs font-semibold text-primary">{account.name.slice(0,2).toUpperCase()}</span></div><CurrencyDisplay className="mt-6 block text-xl font-semibold" value={account.balance} hidden={hidden}/></section>;}
export function MovementIcon({type}:{type:'income'|'expense'}) {return <span className={cn('flex size-10 shrink-0 items-center justify-center rounded-xl',type==='income'?'bg-positive/10 text-positive':'bg-negative/10 text-negative')}>{type==='income'?<ArrowUpRight className="size-4"/>:<ArrowDownRight className="size-4"/>}</span>;}
